version: '3.8'
services:
  web-multas:
    build: .
    container_name: gestor-multas-simit
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - base_de_datos_multas:/app/data
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  base_de_datos_multas:
